print("helloworld")
print("helloworld")
print("helloworld")
print("helloworld")
print("hello kms")
print("hello kms")
print("hello kms")
print("hello kms")
print("hello a;sdlkfj")
print("asdf")
print()
print()