print("helloworld")
print("helloworld")
print("helloworld")
print("helloworld")
print("hello kms")
print("hello kms")
print("hello kms")
print("hello kms")
print("hello a;sdlkfj")
print("asdf")
print()
print()
print("이제 좀 되나?")